### ISSUE TITLE
Red Wall Error Message

### ISSUE THREAD

**Issue by VikingTechLLC** [ltdrdata/ComfyUI-Workflow-Component#8]
Will start by  a disclaimer that this may be a standalone circumstance, given my workflow outlay.

I built out an entire workflow, base generation > hires Fix > face fix > tiled upscaling.  To make it more versatile, I added simple reroute jumpers between each process where I break the image output going to the next process.  This does under normal circumstances highlight those nodes stating they are missing an input, but allows the other nodes to still run through the process and complete those flows.  
After I downloaded your pack, just even having the folder in my custom_nodes folder and running the same above process (even without yet implementing any nodes within my flow), instead of the UI highlighting those same nodes, it just throws up a redwall error and doesn't allow any processing to begin.  Removing the folder and reloading, then back to working.

below images: 
--redwall error message after adding Workflow Component to custom_nodes folder
--highlighted node with arrows showing my jumper from image output to input for next process. 
![Redwall error with Component pack in custom_nodes](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/84103587/2074ca66-bf5f-4d3d-a556-be2b1e7173c7)
![Highlighted error without Component pack in custom_nodes](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/84103587/00e8141c-527f-40e0-b34a-008b4bfd9c42)

**Comment by ltdrdata** [comment]
Thank you for the report. I'll check it.

**Comment by WinstonWoof** [comment]
Get the same issue even in a workflow where I dont have one of the Workflow-Component Nodes enabled.

Only way I've found to resolve it is to play musical folders and restart comfy between workflows where I need i it and workflows where I dont

**Comment by ltdrdata** [comment]
I'd checked. This is not the Workflow Component related issue.
[error.json.txt](https://github.com/ltdrdata/ComfyUI-Workflow-Component/files/12135204/error.json.txt)

Maybe you can reproduce same error with this workflow.
At first it seems working well. But 2nd queue will cause that error.

It's a problem recently introduced in ComfyUI.
Currently, there is an ongoing PR to improve the execution. With the application of that PR, I expect improvements to be made.

**Comment by WinstonWoof** [comment]
Thanks for the update but still leaves the question:

If it is a Core ComfyUI issue how come it only happens if I have  the "Workflow-Component Nodes" folder in "custom_nodes" ?

As soon as I delete it from there it doesn't happen

NB as stated above I get the Red Wall even in Workflows that have no Component Nodes Present just by having the folder present in custom_nodes.

Delete the folder, problem goes away.

**Comment by ltdrdata** [comment]
> Thanks for the update but still leaves the question:
> 
> If it is a Core ComfyUI issue how come it only happens if I have the "Workflow-Component Nodes" folder in "custom_nodes" ?
> 
> As soon as I delete it from there it doesn't happen
> 
> NB as stated above I get the Red Wall even in Workflows that have no Component Nodes Present just by having the folder present in custom_nodes.
> 
> Delete the folder, problem goes away.

I'd tested that. Actually, It is random thing.
In my case, when I moved all the custom nodes outside, the issue that was easily reproducible seemed to disappear. However, when I put them back again, there was still an issue that couldn't be reproduced.

**Comment by pvp-by** [comment]
After installing the extension, I immediately encountered the same error (as the author) in my current workflow. I couldn't have any "Workflow-Component" on my workflow. After trying to understand what was going on, I disabled all extensions except for "ComfyUI-Manager" and encountered the following issues:

There is leftover clutter in the context menu (see Figure 1).
There are buttons remaining in the Queue menu panel (see Figure 2).
Figure 3 shows which nodes are missing, but there is no "Workflow-Component" related node present on the workspace.

![Figure_1_2_3](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/10133995/c599cc8a-6e9a-4e20-8f3d-49ae1cc49bae)

Add info : "ComfyUI\web\extensions"
Additionally, I noticed that the copied "js" files are not blocked or deleted in any way after disabling the extension or removing it (I assume there is no cleanup mechanism in ComfyUI). Otherwise, I can't understand how and where the clutter remains in the menu, queue panel, etc.

----
✔ I checked and confirm - by deleting all folders from "ComfyUI\web\extensions" except for "core" and "manager," the glitches disappeared from the menu and similar elements (see Figure 1, Figure 2).

**Comment by WinstonWoof** [comment]
@pvp-by  Ahhh I have those 2 options left as well even after Deleting the enitire Workflow Component folder.

Wonder if Its because Manager is from the same author??

**Comment by pvp-by** [comment]
@ltdrdata 
I want to point out that adding "Workflow-Component" as an extension (by the way, it's not visible in your manager) causes incorrect behavior in ComfyUI (if the extension functions correctly, it is the one that breaks the logic of ComfyUI's operation. Please don't take it personally; it's purely informational).

Here's another example: In this case, it is visible that the node is in "MUTED" status, but the "Workflow-Component" makes ComfyUI ignore it.

![Figure_4](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/10133995/aa1f4abb-6926-44af-be9d-b4e7ed7c80be)

PS: I'm not sure if all my messages should be in this "issue." I apologize for that.
PS: Without any extensions, the Mode > "Never" does not work for the "reroute" node [#965](https://github.com/comfyanonymous/ComfyUI/issues/965).

You mentioned that there is a certain PR that you are waiting for in ComfyUI. Can you provide a link to it (at least for testing purposes to see if it fixes the situation)?

**Comment by ltdrdata** [comment]
currently there is 2 PR.

This is new one. And I'll adopt to workflow component eventually. But, it is little bit unstable now. This solves above issue. But, it seems not perfect. I have experienced randomly. If you can reproduce that issue on that PR, persistently. Please report to there.

https://github.com/comfyanonymous/ComfyUI/pull/931


And this is my old PR. This will fix that issue including muting issue. This PR has certain approach to avoid that issue. And workflow components uses this code internally.

https://github.com/comfyanonymous/ComfyUI/pull/731

I'll abandon this after 931 is stablized enough.

**Comment by worthy7** [comment]
I have this issue.
